# Generated by Django 5.0.4 on 2024-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_category_checkout_product_orderedproduct_addtocart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_checkout',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
